parameters:
#    theme_core.example.class: Theme\CoreBundle\Example

services:
#    theme_core.example:
#        class: %theme_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
